// Code generated by "stringer -type=Direction"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[READ-0]
	_ = x[WRITE-1]
	_ = x[APPEND-2]
	_ = x[HERE-3]
}

const _Direction_name = "READWRITEAPPENDHERE"

var _Direction_index = [...]uint8{0, 4, 9, 15, 19}

func (i Direction) String() string {
	if i < 0 || i >= Direction(len(_Direction_index)-1) {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
