// Code generated by "stringer -type=LexType"; DO NOT EDIT.

package ast

import "strconv"

const _LexType_name = "WORDREDIRSIMPLELISTBLOCKASYNCVARTUPLEASSIGNIFFORANDANDOROR"

var _LexType_index = [...]uint8{0, 4, 9, 15, 19, 24, 29, 32, 37, 43, 45, 48, 54, 58}

func (i LexType) String() string {
	if i < 0 || i >= LexType(len(_LexType_index)-1) {
		return "LexType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LexType_name[_LexType_index[i]:_LexType_index[i+1]]
}
